In [2]:
import pandas as pd

In [11]:
import numpy as np

In [4]:
a=pd.read_csv('ForTesting.csv')

In [5]:
df=pd.DataFrame(a)

In [4]:
df.head()

,Unnamed: 0,patient_id,visit_date,doctor_id,doctor_name,department,admission_type,treatment_type,wait_time_min,treatment_cost,hospital_stay_days,readmission_30d,patient_satisfaction,doctor_rating,insurance_claim,revenue_generated
0,0,P00001,2024/03/06,D109,Dr. Brown,Pediatrics,Routine,Surgery,55,19614,4,1,5.0,1.0,1,10486
1,1,P00002,2024-01-17,D107,Dr. Patel,Orthopedics,Emergency,Medication,105,12882,4,FALSE,2.0,NaN,Yes,7512
2,2,P00003,2024-03-31,D117,Dr. Smith,Neurology,Routine,Medication,NaN,19332,NaN,0,1.0,1.0,Yes,22020
3,3,P00004,2024/03/28,D119,Dr. Chen,Pediatrics,emergency,Surgery,20,23191,10,FALSE,3.0,NaN,FALSE,13192
4,4,P00005,2024/04/13,D113,Dr. Adams,Cardiology,Referral,surgery,80,22668,15,Yes,5.0,3.0,FALSE,6724

In [5]:
df['visit_date']

0        2024/03/06
1        2024-01-17
2        2024-03-31
3        2024/03/28
4        2024/04/13
            ...
20295    2024/01/05
20296    16/03/2024
20297    2024-03-28
20298    02/03/2024
20299    06-03-2024
Name: visit_date, Length: 20300, dtype: object

In [7]:
df['visit_date'] = pd.to_datetime(df['visit_date'], format='mixed')

In [8]:
df['visit_date']

0       2024-03-06
1       2024-01-17
2       2024-03-31
3       2024-03-28
4       2024-04-13
           ...
20295   2024-01-05
20296   2024-03-16
20297   2024-03-28
20298   2024-02-03
20299   2024-06-03
Name: visit_date, Length: 20300, dtype: datetime64[ns]

In [10]:
df

,Unnamed: 0,patient_id,visit_date,doctor_id,doctor_name,department,admission_type,treatment_type,wait_time_min,treatment_cost,hospital_stay_days,readmission_30d,patient_satisfaction,doctor_rating,insurance_claim,revenue_generated
0,0,P00001,2024-03-06,D109,Dr. Brown,Pediatrics,Routine,Surgery,55,19614,4,1,5.0,1.0,1,10486
1,1,P00002,2024-01-17,D107,Dr. Patel,Orthopedics,Emergency,Medication,105,12882,4,FALSE,2.0,NaN,Yes,7512
2,2,P00003,2024-03-31,D117,Dr. Smith,Neurology,Routine,Medication,NaN,19332,NaN,0,1.0,1.0,Yes,22020
3,3,P00004,2024-03-28,D119,Dr. Chen,Pediatrics,emergency,Surgery,20,23191,10,FALSE,3.0,NaN,FALSE,13192
4,4,P00005,2024-04-13,D113,Dr. Adams,Cardiology,Referral,surgery,80,22668,15,Yes,5.0,3.0,FALSE,6724
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20295,20295,P00448,2024-01-05,D103,Dr. Taylor,Pediatrics,ROUTINE,Therapy,86,24760,4,Yes,1.0,NaN,0,22002
20296,20296,P17278,2024-03-16,D115,Dr. Smith,cardiology,ROUTINE,Therapy,9,22762,4,0,3.0,4.0,0,21655
20297,20297,P05454,2024-03-28,D111,Dr. Brown,Pediatrics,ROUTINE,Therapy,20,24157,3,TRUE,2.0,4.0,Yes,21049
20298,20298,P03212,2024-02-03,D104,Dr. Patel,Orthopedics,ROUTINE,Surgery,NaN,24484,6,FALSE,3.0,2.0,TRUE,4442
20299,20299,P05562,2024-06-03,D100,Dr. Lee,Neurology,Routine,Therapy,102,19561,8,Yes,NaN,NaN,TRUE,15084

In [11]:
df[['admission_type','treatment_type']].head()

  admission_type treatment_type
0        Routine        Surgery
1      Emergency     Medication
2        Routine     Medication
3      emergency        Surgery
4       Referral        surgery

In [12]:
df['admission_type']=df['admission_type'].str.capitalize()

In [13]:
df['admission_type'].head()

0      Routine
1    Emergency
2      Routine
3    Emergency
4     Referral
Name: admission_type, dtype: object

## Converting object to int to perform mean, on missing values

In [ ]:
df['wait_time_min'] = pd.to_numeric(df['wait_time_min'], errors='coerce').astype(np.int64)

In [13]:
df['wait_time_min'].fillna(df['wait_time_min'].mean(),inplace=True)

In [30]:
print(df.dtypes)

Unnamed: 0              float64
patient_id               object
visit_date               object
doctor_id                object
doctor_name              object
department               object
admission_type           object
treatment_type           object
wait_time_min           float64
treatment_cost           object
hospital_stay_days       object
readmission_30d          object
patient_satisfaction    float64
doctor_rating           float64
insurance_claim          object
revenue_generated         int64
dtype: object

In [28]:
df['wait_time_min'].isnull().sum()

np.int64(0)

In [24]:
df['wait_time_min'] = df['wait_time_min'].replace(0, np.nan)

In [27]:
df['wait_time_min'] = df['wait_time_min'].fillna(df['wait_time_min'].mean())

In [34]:
df['treatment_cost'] = pd.to_numeric(df['treatment_cost'], errors='coerce').fillna(0).astype(np.int64)

In [35]:
df['treatment_cost'] = df['treatment_cost'].replace(0, np.nan)

In [36]:
df['treatment_cost'] = df['treatment_cost'].fillna(df['treatment_cost'].mean())

In [37]:
df['treatment_cost'].isnull().sum()

np.int64(0)

In [38]:
df['treatment_cost'].head(20)

0     19614.0
1     12882.0
2     19332.0
3     23191.0
4     22668.0
5     24967.0
6     13443.0
7      5684.0
8      4213.0
9      3015.0
10     7114.0
11     8806.0
12     4895.0
13    10622.0
14    13828.0
15    13401.0
16     3144.0
17    18693.0
18    11630.0
19     4779.0
Name: treatment_cost, dtype: float64

In [40]:
df['treatment_cost'].dtypes

dtype('float64')

In [54]:
def fix(x):
    if x in ['1','Yes','TRUE']:
        return 'Yes'
    else:
        return 'No'

In [55]:
df['readmission_30d'] = df['readmission_30d'].apply(fix)

In [57]:
df['readmission_30d'].value_counts()

readmission_30d
No     10204
Yes    10096
Name: count, dtype: int64

In [68]:
df['patient_satisfaction'].fillna(df['patient_satisfaction'].mean,inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_23880\3268668800.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method Series.mean of 0        5.0
1        2.0
2        1.0
3        3.0
4        5.0
        ...
20295    1.0
20296    3.0
20297    2.0
20298    3.0
20299    NaN
Name: patient_satisfaction, Length: 20300, dtype: float64>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['patient_satisfaction'].fillna(df['patient_satisfaction'].mean,inplace=True)

In [66]:
df['patient_satisfaction'].replace(0.0,np.nan,inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_23880\3322005940.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['patient_satisfaction'].replace(0.0,np.nan,inplace=True)

In [75]:
df

RecursionError: maximum recursion depth exceeded

RecursionError: maximum recursion depth exceeded

In [73]:
df['patient_satisfaction'].isnull().sum()

np.int64(0)